tasks:
  - name: npm part
    init: npm install
    # to wait a bit from mongo db start. Note: gp-await not possible here since db is long running
    command: sleep 3 && npm run development
  - name: docker mongodb part
    init: docker pull mongo
    command: docker run -p 27017:27017 mongo
    openMode: split-right
ports:
  - port: 3000
    visibility: private
    onOpen: open-preview


vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix